apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cep-project2-network-policy
  namespace: cep-project2
spec:
  podSelector:
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
