apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewaccess-binding
  namespace: cep-project2
subjects:
- kind: User
  name: user4
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: viewaccess
  apiGroup: rbac.authorization.k8s.io
